### PR TITLE
Remove dependency on assert

### PR DESCRIPTION
**Pull request by jamesplease**
The tests prob. need to be updated, but this makes this thing work in browserz

### CODE REVIEW

**Comment by jamesplease** [comment]
Actually – it could just use the `callable` fn.

**Comment by tbranyen** [comment]
I've been doing this lately: `browserify -r assert -s assert -o assert.js` and then:

``` js
var assert = require('./assert')
```

Granted this PR adds another file to commit, but it does work in browser/node.

**Comment by jamesplease** [comment]
That's pretty cool, @tbranyen ; I hadn't thought of doing that. With that said, sending down the entire assert module to the browser simply to verify that a variable is a function seems a lil inefficient to me. What do you think?

**Comment by tbranyen** [comment]
Yeah could be overkill, esp. if this module doesn't balloon out with edge case fixes.

**Comment by callum** [comment]
I hadn't actually seen this until I had already done it. Thanks @jmeas

**Comment by jamesplease** [comment]
np ✌️

**Pull request closed without merging**
